import { useState } from 'react';
import { 
  ChevronLeft, 
  Download, 
  Calendar,
  Clock,
  FileText,
  Share2,
  ChevronRight
} from 'lucide-react';
import { useAppStore } from '../store/appStore';
import { format } from 'date-fns';
import type { EmergencyEvent } from '../types';
import { protocols } from '../data/protocols';

export function EventReports() {
  const { eventHistory, setScreen } = useAppStore();
  const [selectedEvent, setSelectedEvent] = useState<EmergencyEvent | null>(null);

  const formatDate = (dateString: string) => {
    return format(new Date(dateString), 'dd MMM yyyy HH:mm');
  };

  const formatDuration = (start: string, events: EmergencyEvent['events']) => {
    if (events.length < 2) return 'N/A';
    const startTime = new Date(start).getTime();
    const endTime = new Date(events[events.length - 1].timestamp).getTime();
    const diffMs = endTime - startTime;
    const mins = Math.floor(diffMs / 60000);
    const secs = Math.floor((diffMs % 60000) / 1000);
    return `${mins}m ${secs}s`;
  };

  const getProtocolTitle = (protocolId: string) => {
    return protocols.find(p => p.id === protocolId)?.title || protocolId;
  };

  // Semantic colour per event type (colour + label, never colour alone).
  const eventColor = (type: string) =>
    type === 'drug_given' ? 'var(--drug)' :
    type === '999_called' ? 'var(--red)' :
    type === 'shock_delivered' ? 'var(--decision)' :
    type === 'step_completed' ? 'var(--green)' :
    type === 'rosc' ? 'var(--brand)' :
    'var(--roles)';

  const generateReport = (event: EmergencyEvent) => {
    const protocol = protocols.find(p => p.id === event.protocol_id);
    
    const report = `
EMERGENCY INCIDENT REPORT
=========================
Generated: ${format(new Date(), 'dd MMMM yyyy HH:mm')}

INCIDENT DETAILS
----------------
Date/Time: ${formatDate(event.timestamp)}
Protocol: ${protocol?.title || event.protocol_id}
Protocol Version: ${event.protocol_version}
Duration: ${formatDuration(event.timestamp, event.events)}
Outcome: ${event.outcome || 'Not recorded'}

EVENT LOG
---------
${event.events.map(e => `${format(new Date(e.timestamp), 'HH:mm:ss')} - ${e.label}${e.details ? ` (${e.details})` : ''}`).join('\n')}

NOTES
-----
${event.notes || 'No notes recorded'}

---
This report was generated by ResusIQ.
Protocols based on Resuscitation Council UK 2025 & SDCEP guidance.
For audit and training purposes only.
    `.trim();

    return report;
  };

  const handleExport = (event: EmergencyEvent) => {
    const report = generateReport(event);
    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `emergency-report-${format(new Date(event.timestamp), 'yyyy-MM-dd-HHmm')}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleShare = async (event: EmergencyEvent) => {
    const report = generateReport(event);
    
    if (navigator.share) {
      try {
        await navigator.share({
          title: 'Emergency Incident Report',
          text: report,
        });
      } catch (err) {
        // User cancelled or error
      }
    } else {
      // Fallback: copy to clipboard
      navigator.clipboard.writeText(report);
      alert('Report copied to clipboard');
    }
  };

  if (selectedEvent) {
    const protocol = protocols.find(p => p.id === selectedEvent.protocol_id);

    return (
      <div className="min-h-screen flex flex-col safe-area-top" style={{ background: 'var(--bg)', color: 'var(--text-1)' }}>
        <header className="flex items-center gap-3 px-4" style={{ height: 'var(--appbar-h)' }}>
          <button
            onClick={() => setSelectedEvent(null)}
            aria-label="Back"
            className="w-11 h-11 rounded-xl flex items-center justify-center active:opacity-80 transition-opacity"
            style={{ background: 'var(--surface-2)', border: '1px solid var(--border)' }}
          >
            <ChevronLeft className="w-5 h-5" style={{ color: 'var(--text-2)' }} />
          </button>
          <div className="flex-1">
            <h1 className="font-bold" style={{ color: 'var(--text-1)' }}>{protocol?.title}</h1>
            <p className="cs-eyebrow mt-0.5">{formatDate(selectedEvent.timestamp)}</p>
          </div>
        </header>

        <main className="flex-1 p-4 overflow-y-auto">
          {/* Summary */}
          <div className="cs-card p-4 mb-4">
            <h2 className="cs-eyebrow mb-3">Summary</h2>
            <div className="grid grid-cols-2 gap-4 text-sm">
              <div>
                <p style={{ color: 'var(--text-3)' }}>Duration</p>
                <p className="cs-numeric font-medium" style={{ color: 'var(--text-1)' }}>{formatDuration(selectedEvent.timestamp, selectedEvent.events)}</p>
              </div>
              <div>
                <p style={{ color: 'var(--text-3)' }}>Events Logged</p>
                <p className="cs-numeric font-medium" style={{ color: 'var(--text-1)' }}>{selectedEvent.events.length}</p>
              </div>
              <div>
                <p style={{ color: 'var(--text-3)' }}>Outcome</p>
                <p className="font-medium" style={{ color: 'var(--text-1)' }}>{selectedEvent.outcome || 'Not recorded'}</p>
              </div>
              <div>
                <p style={{ color: 'var(--text-3)' }}>Protocol Version</p>
                <p className="cs-numeric font-medium" style={{ color: 'var(--text-1)' }}>{selectedEvent.protocol_version}</p>
              </div>
            </div>
          </div>

          {/* Timeline */}
          <div className="cs-card p-4 mb-4">
            <h2 className="cs-eyebrow mb-3">Event Timeline</h2>
            <div className="space-y-3">
              {selectedEvent.events.map((event, idx) => (
                <div key={event.id} className="flex gap-3">
                  <div className="flex flex-col items-center">
                    <div className="w-3 h-3 rounded-full" style={{ background: eventColor(event.type) }} />
                    {idx < selectedEvent.events.length - 1 && (
                      <div className="w-0.5 flex-1 my-1" style={{ background: 'var(--surface-3)' }} />
                    )}
                  </div>
                  <div className="flex-1 pb-3">
                    <p className="font-medium" style={{ color: 'var(--text-1)' }}>{event.label}</p>
                    <p className="cs-numeric text-xs" style={{ color: 'var(--text-3)' }}>
                      {format(new Date(event.timestamp), 'HH:mm:ss')}
                    </p>
                    {event.details && (
                      <p className="text-sm" style={{ color: 'var(--text-3)' }}>{event.details}</p>
                    )}
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Notes */}
          {selectedEvent.notes && (
            <div className="cs-card p-4 mb-4">
              <h2 className="cs-eyebrow mb-2">Notes</h2>
              <p style={{ color: 'var(--text-2)' }}>{selectedEvent.notes}</p>
            </div>
          )}
        </main>

        {/* Footer */}
        <footer className="p-4 safe-area-bottom">
          <div className="grid grid-cols-2 gap-3">
            <button
              onClick={() => handleExport(selectedEvent)}
              className="p-3 rounded-xl font-bold flex items-center justify-center gap-2 active:opacity-90 transition-opacity"
              style={{ background: 'var(--brand)', color: 'var(--text-on-light)', minHeight: 'var(--touch-min)' }}
            >
              <Download className="w-5 h-5" />
              Export
            </button>
            <button
              onClick={() => handleShare(selectedEvent)}
              className="p-3 rounded-xl font-bold flex items-center justify-center gap-2 active:opacity-80 transition-opacity"
              style={{ background: 'var(--surface-2)', border: '1px solid var(--border)', color: 'var(--text-2)', minHeight: 'var(--touch-min)' }}
            >
              <Share2 className="w-5 h-5" />
              Share
            </button>
          </div>
        </footer>
      </div>
    );
  }

  return (
    <div className="min-h-screen flex flex-col safe-area-top" style={{ background: 'var(--bg)', color: 'var(--text-1)' }}>
      <header className="flex items-center gap-3 px-4" style={{ height: 'var(--appbar-h)' }}>
        <button
          onClick={() => setScreen('home')}
          aria-label="Back"
          className="w-11 h-11 rounded-xl flex items-center justify-center active:opacity-80 transition-opacity"
          style={{ background: 'var(--surface-2)', border: '1px solid var(--border)' }}
        >
          <ChevronLeft className="w-5 h-5" style={{ color: 'var(--text-2)' }} />
        </button>
        <div>
          <h1 className="text-xl font-bold" style={{ color: 'var(--text-1)' }}>Event Reports</h1>
          <p className="cs-eyebrow mt-0.5">{eventHistory.length} incidents recorded</p>
        </div>
      </header>

      <main className="flex-1 p-4 overflow-y-auto">
        {eventHistory.length === 0 ? (
          <div className="flex flex-col items-center justify-center h-64" style={{ color: 'var(--text-3)' }}>
            <FileText className="w-16 h-16 mb-4 opacity-50" />
            <p className="text-lg">No incidents recorded yet</p>
            <p className="text-sm">Events will appear here after emergencies</p>
          </div>
        ) : (
          <div className="space-y-3">
            {[...eventHistory].reverse().map((event) => (
              <button
                key={event.id}
                onClick={() => setSelectedEvent(event)}
                className="w-full cs-card p-4 text-left active:opacity-90 transition-opacity"
              >
                <div className="flex items-center justify-between">
                  <div className="flex-1">
                    <h3 className="font-bold" style={{ color: 'var(--text-1)' }}>{getProtocolTitle(event.protocol_id)}</h3>
                    <div className="flex items-center gap-4 text-sm mt-1" style={{ color: 'var(--text-3)' }}>
                      <span className="flex items-center gap-1">
                        <Calendar className="w-4 h-4" />
                        {format(new Date(event.timestamp), 'dd MMM yyyy')}
                      </span>
                      <span className="cs-numeric flex items-center gap-1">
                        <Clock className="w-4 h-4" />
                        {format(new Date(event.timestamp), 'HH:mm')}
                      </span>
                    </div>
                  </div>
                  <ChevronRight className="w-5 h-5" style={{ color: 'var(--text-3)' }} />
                </div>
                <div className="flex gap-2 mt-2">
                  <span className="px-2 py-1 rounded text-xs" style={{ background: 'var(--surface-3)', color: 'var(--text-2)' }}>
                    {event.events.length} events
                  </span>
                  {event.completed && (
                    <span className="px-2 py-1 rounded text-xs" style={{ background: 'var(--green-tint)', color: 'var(--green)' }}>
                      Completed
                    </span>
                  )}
                </div>
              </button>
            ))}
          </div>
        )}
      </main>
    </div>
  );
}
