import { useState } from 'react';
import {
  ArrowLeft,
  Download,
  Calendar,
  Clock,
  FileText,
  Share2,
  ChevronRight
} from 'lucide-react';
import { useAppStore } from '../store/appStore';
import { format } from 'date-fns';
import type { EmergencyEvent, EventOutcome } from '../types';
import { OUTCOME_TRAINING_DRILL, OUTCOME_UNRESUMABLE } from '../types';
import { protocols } from '../data/protocols';

// What each stored outcome is CALLED in front of a human. Nothing on this
// screen leaves the building as a raw token: the exported incident report goes
// to a practice review, a defence union or a coroner, and "Outcome:
// unresumable" is an internal enum handed to someone with no way to read it.
//
// Imported constants, never re-typed literals: a typo here would quietly fall
// through to the default and print the token anyway.
const OUTCOME_LABEL: Record<EventOutcome, string> = {
  [OUTCOME_UNRESUMABLE]: 'Record closed — the app restarted and the guide could not be resumed',
  [OUTCOME_TRAINING_DRILL]: 'Training drill',
};

// The parameter is a loose string on purpose. `outcome` is typed, but these
// records come off disk, where a blob written by another build (or by hand) can
// hold anything — showing that value unchanged beats showing nothing.
const outcomeLabel = (outcome?: string): string =>
  outcome ? OUTCOME_LABEL[outcome as EventOutcome] ?? outcome : 'Not recorded';

export function EventReports() {
  const { eventHistory, setScreen } = useAppStore();
  const [selectedEvent, setSelectedEvent] = useState<EmergencyEvent | null>(null);

  const formatDate = (dateString: string) => {
    return format(new Date(dateString), 'dd MMM yyyy HH:mm');
  };

  const formatDuration = (start: string, events: EmergencyEvent['events']) => {
    if (events.length < 2) return 'N/A';
    const startTime = new Date(start).getTime();
    const endTime = new Date(events[events.length - 1].timestamp).getTime();
    const diffMs = endTime - startTime;
    const mins = Math.floor(diffMs / 60000);
    const secs = Math.floor((diffMs % 60000) / 1000);
    return `${mins}m ${secs}s`;
  };

  // Every heading in this screen — list row, detail header, exported report —
  // comes through here, so an unresolvable id can never render as a blank title
  // or as a bare machine token on a medico-legal record. A salvaged stub is
  // stored as 'unknown' (see the store's merge); an id that simply no longer
  // exists in the data keeps its id alongside the wording, because that is the
  // only thing left saying which emergency this was.
  const getProtocolTitle = (protocolId: string) => {
    const title = protocols.find(p => p.id === protocolId)?.title;
    if (title) return title;
    return protocolId && protocolId !== 'unknown'
      ? `Emergency — record incomplete (${protocolId})`
      : 'Emergency — record incomplete';
  };

  // Semantic colour per event type (colour + label, never colour alone).
  const eventColor = (type: string) =>
    type === 'drug_given' ? 'var(--drug)' :
    type === '999_called' ? 'var(--red)' :
    type === 'shock_delivered' ? 'var(--decision)' :
    type === 'step_completed' ? 'var(--green)' :
    type === 'rosc' ? 'var(--brand)' :
    'var(--roles)';

  const generateReport = (event: EmergencyEvent) => {
    const report = `
EMERGENCY INCIDENT REPORT
=========================
Generated: ${format(new Date(), 'dd MMMM yyyy HH:mm')}

INCIDENT DETAILS
----------------
Date/Time: ${formatDate(event.timestamp)}
Protocol: ${getProtocolTitle(event.protocol_id)}
Protocol Version: ${event.protocol_version}
Duration: ${formatDuration(event.timestamp, event.events)}
Outcome: ${outcomeLabel(event.outcome)}

EVENT LOG
---------
${event.events.map(e => `${format(new Date(e.timestamp), 'HH:mm:ss')} - ${e.label}${e.details ? ` (${e.details})` : ''}`).join('\n')}

NOTES
-----
${event.notes || 'No notes recorded'}

---
This report was generated by ResusIQ.
Protocols based on Resuscitation Council UK 2025 & SDCEP guidance.
For audit and training purposes only.
    `.trim();

    return report;
  };

  const handleExport = (event: EmergencyEvent) => {
    const report = generateReport(event);
    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `emergency-report-${format(new Date(event.timestamp), 'yyyy-MM-dd-HHmm')}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleShare = async (event: EmergencyEvent) => {
    const report = generateReport(event);

    if (navigator.share) {
      try {
        await navigator.share({
          title: 'Emergency Incident Report',
          text: report,
        });
      } catch (err) {
        // User cancelled or error
      }
    } else {
      // Fallback: copy to clipboard
      navigator.clipboard.writeText(report);
      alert('Report copied to clipboard');
    }
  };

  const eyebrowStyle = {
    fontSize: 'var(--fs-label)',
    fontWeight: 700,
    letterSpacing: 'var(--ls-label)',
    textTransform: 'uppercase' as const,
    color: 'var(--brand)',
  };

  if (selectedEvent) {
    return (
      <div className="riq-ward-focus min-h-screen flex flex-col safe-area-top" style={{ background: 'var(--bg)', color: 'var(--text-1)' }}>
        <header className="flex items-center gap-3 px-6" style={{ height: 'var(--appbar-h)' }}>
          <button
            onClick={() => setSelectedEvent(null)}
            aria-label="Back"
            className="flex items-center justify-center active:opacity-70 transition-opacity"
            style={{ width: 56, height: 56, background: 'transparent', border: 'none' }}
          >
            <ArrowLeft className="w-7 h-7" style={{ color: 'var(--text-2)' }} />
          </button>
          <div className="flex-1">
            <h1 className="font-bold" style={{ color: 'var(--text-1)', fontSize: 'var(--fs-body)' }}>{getProtocolTitle(selectedEvent.protocol_id)}</h1>
            <p className="mt-0.5" style={{ color: 'var(--text-3)', fontSize: 'var(--fs-caption)' }}>{formatDate(selectedEvent.timestamp)}</p>
          </div>
        </header>

        <main className="flex-1 px-6 pb-6 overflow-y-auto" style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
          {/* Summary */}
          <div
            className="p-6"
            style={{ background: 'var(--surface)', boxShadow: 'var(--shadow-sm)', borderRadius: 'var(--radius-lg)' }}
          >
            <h2 style={{ ...eyebrowStyle, marginBottom: 16 }}>Summary</h2>
            <div className="grid grid-cols-2" style={{ gap: 16 }}>
              <div>
                <p style={{ color: 'var(--text-3)', fontSize: 'var(--fs-caption)' }}>Duration</p>
                <p className="cs-numeric" style={{ color: 'var(--text-1)', fontSize: 'var(--fs-body-sm)', fontWeight: 600 }}>{formatDuration(selectedEvent.timestamp, selectedEvent.events)}</p>
              </div>
              <div>
                <p style={{ color: 'var(--text-3)', fontSize: 'var(--fs-caption)' }}>Events logged</p>
                <p className="cs-numeric" style={{ color: 'var(--text-1)', fontSize: 'var(--fs-body-sm)', fontWeight: 600 }}>{selectedEvent.events.length}</p>
              </div>
              <div>
                <p style={{ color: 'var(--text-3)', fontSize: 'var(--fs-caption)' }}>Outcome</p>
                <p style={{ color: 'var(--text-1)', fontSize: 'var(--fs-body-sm)', fontWeight: 600 }}>{outcomeLabel(selectedEvent.outcome)}</p>
              </div>
              <div>
                <p style={{ color: 'var(--text-3)', fontSize: 'var(--fs-caption)' }}>Protocol version</p>
                <p className="cs-numeric" style={{ color: 'var(--text-1)', fontSize: 'var(--fs-body-sm)', fontWeight: 600 }}>{selectedEvent.protocol_version}</p>
              </div>
            </div>
          </div>

          {/* Timeline */}
          <div
            className="p-6"
            style={{ background: 'var(--surface)', boxShadow: 'var(--shadow-sm)', borderRadius: 'var(--radius-lg)' }}
          >
            <h2 style={{ ...eyebrowStyle, marginBottom: 16 }}>Event timeline</h2>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
              {selectedEvent.events.map((event) => (
                <div
                  key={event.id}
                  className="flex items-start gap-3 p-4"
                  style={{ background: 'var(--surface-2)', borderRadius: 'var(--radius-md)' }}
                >
                  <div
                    className="mt-1.5 rounded-full flex-shrink-0"
                    style={{ width: 12, height: 12, background: eventColor(event.type) }}
                  />
                  <div className="flex-1">
                    <p
                      className="cs-numeric"
                      style={{ color: 'var(--brand)', fontSize: 'var(--fs-caption)', fontWeight: 700, letterSpacing: 'var(--ls-label)' }}
                    >
                      {format(new Date(event.timestamp), 'HH:mm:ss')}
                    </p>
                    <p style={{ color: 'var(--text-1)', fontSize: 'var(--fs-body-sm)', fontWeight: 600 }}>{event.label}</p>
                    {event.details && (
                      <p style={{ color: 'var(--text-2)', fontSize: 'var(--fs-caption)' }}>{event.details}</p>
                    )}
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Notes */}
          {selectedEvent.notes && (
            <div
              className="p-6"
              style={{ background: 'var(--surface)', boxShadow: 'var(--shadow-sm)', borderRadius: 'var(--radius-lg)' }}
            >
              <h2 style={{ ...eyebrowStyle, marginBottom: 12 }}>Notes</h2>
              <p style={{ color: 'var(--text-2)', fontSize: 'var(--fs-body-sm)' }}>{selectedEvent.notes}</p>
            </div>
          )}
        </main>

        {/* Footer */}
        <footer className="px-6 pb-6 safe-area-bottom">
          <div className="grid grid-cols-2" style={{ gap: 12 }}>
            <button
              onClick={() => handleExport(selectedEvent)}
              className="flex items-center justify-center gap-2 active:opacity-90 transition-opacity"
              style={{
                background: 'var(--brand)',
                color: '#fff',
                boxShadow: 'var(--shadow-btn)',
                borderRadius: 'var(--radius-lg)',
                border: 'none',
                minHeight: 'var(--touch-min)',
                fontSize: 'var(--fs-body-sm)',
                fontWeight: 700,
              }}
            >
              <Download className="w-5 h-5" />
              Export
            </button>
            <button
              onClick={() => handleShare(selectedEvent)}
              className="flex items-center justify-center gap-2 active:opacity-80 transition-opacity"
              style={{
                background: 'var(--surface)',
                border: '1px solid var(--border)',
                color: 'var(--text-2)',
                boxShadow: 'var(--shadow-sm)',
                borderRadius: 'var(--radius-lg)',
                minHeight: 'var(--touch-min)',
                fontSize: 'var(--fs-body-sm)',
                fontWeight: 700,
              }}
            >
              <Share2 className="w-5 h-5" />
              Share
            </button>
          </div>
        </footer>
      </div>
    );
  }

  return (
    <div className="riq-ward-focus min-h-screen flex flex-col safe-area-top" style={{ background: 'var(--bg)', color: 'var(--text-1)' }}>
      <header className="flex items-center gap-3 px-6" style={{ height: 'var(--appbar-h)' }}>
        <button
          onClick={() => setScreen('home')}
          aria-label="Back"
          className="flex items-center justify-center active:opacity-70 transition-opacity"
          style={{ width: 56, height: 56, background: 'transparent', border: 'none' }}
        >
          <ArrowLeft className="w-7 h-7" style={{ color: 'var(--text-2)' }} />
        </button>
        <div>
          <h1 className="font-bold" style={{ color: 'var(--text-1)', fontSize: 'var(--fs-body)' }}>Event reports</h1>
          <p className="mt-0.5" style={{ color: 'var(--text-3)', fontSize: 'var(--fs-caption)' }}>{eventHistory.length} incidents recorded</p>
        </div>
      </header>

      <main className="flex-1 px-6 pb-6 overflow-y-auto">
        {eventHistory.length === 0 ? (
          <div className="flex flex-col items-center justify-center h-64" style={{ color: 'var(--text-3)' }}>
            <FileText className="w-16 h-16 mb-4 opacity-50" />
            <p style={{ fontSize: 'var(--fs-lead)', color: 'var(--text-2)', fontWeight: 600 }}>No incidents recorded yet</p>
            <p style={{ fontSize: 'var(--fs-body-sm)' }}>Events will appear here after emergencies</p>
          </div>
        ) : (
          <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
            {[...eventHistory].reverse().map((event) => (
              <button
                key={event.id}
                onClick={() => setSelectedEvent(event)}
                className="w-full text-left active:opacity-90 transition-opacity p-6"
                style={{
                  background: 'var(--surface)',
                  boxShadow: 'var(--shadow-sm)',
                  borderRadius: 'var(--radius-lg)',
                  border: 'none',
                  minHeight: 'var(--touch-comfort)',
                }}
              >
                <div className="flex items-center justify-between gap-3">
                  <div className="flex-1">
                    <h3 className="font-bold" style={{ color: 'var(--text-1)', fontSize: 'var(--fs-body)' }}>{getProtocolTitle(event.protocol_id)}</h3>
                    <div className="flex items-center gap-4 mt-1" style={{ color: 'var(--text-3)', fontSize: 'var(--fs-caption)' }}>
                      <span className="flex items-center gap-1">
                        <Calendar className="w-4 h-4" />
                        {format(new Date(event.timestamp), 'dd MMM yyyy')}
                      </span>
                      <span className="cs-numeric flex items-center gap-1">
                        <Clock className="w-4 h-4" />
                        {format(new Date(event.timestamp), 'HH:mm')}
                      </span>
                    </div>
                  </div>
                  <ChevronRight className="w-5 h-5 flex-shrink-0" style={{ color: 'var(--text-3)' }} />
                </div>
                <div className="flex gap-2 mt-3">
                  <span
                    className="px-3 py-1"
                    style={{ background: 'var(--brand-tint)', color: 'var(--brand)', borderRadius: 'var(--radius-pill)', fontSize: 'var(--fs-caption)', fontWeight: 600 }}
                  >
                    {event.events.length} events
                  </span>
                  {/* Green "Completed" is a claim, and two kinds of record
                      cannot support it.

                      A record closed by a restart: the team never finished this
                      one, the app went away underneath them (clinical review
                      2026-09-20). Amber, and it says what actually happened.

                      A drill: nobody was ever ill. Read six months later in a
                      practice review, an unlabelled drill is a resuscitation
                      that never happened — so it is labelled at a glance, in
                      the calm brand blue rather than a clinical colour. */}
                  {event.completed && (
                    event.outcome === OUTCOME_TRAINING_DRILL ? (
                      <span
                        className="px-3 py-1"
                        style={{ background: 'var(--brand-tint)', color: 'var(--brand)', borderRadius: 'var(--radius-pill)', fontSize: 'var(--fs-caption)', fontWeight: 600 }}
                      >
                        Training drill
                      </span>
                    ) : event.outcome === OUTCOME_UNRESUMABLE ? (
                      <span
                        className="px-3 py-1"
                        style={{ background: 'var(--warn-tint)', color: 'var(--warn)', borderRadius: 'var(--radius-pill)', fontSize: 'var(--fs-caption)', fontWeight: 600 }}
                      >
                        Record closed
                      </span>
                    ) : (
                      <span
                        className="px-3 py-1"
                        style={{ background: 'var(--green-50)', color: 'var(--green-700)', borderRadius: 'var(--radius-pill)', fontSize: 'var(--fs-caption)', fontWeight: 600 }}
                      >
                        Completed
                      </span>
                    )
                  )}
                </div>
              </button>
            ))}
          </div>
        )}
      </main>
    </div>
  );
}
